name: "Pull Request Docs Check"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: |
        sudo apt-get install python3-sphinx
        sphinx-apidoc -f -t doc/template/ -o doc/source/ pathaia
      shell: bash

    - uses: ammaraskar/sphinx-action@0.4
      with:
        pre-build-command: python -m pip install sphinx_rtd_theme sphinx-autodoc-typehints
        docs-folder: "doc/"

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: doc/build/html/
      if: success()
