name: "Pull Request Docs Check"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "doc/"
        pre-build-command: python -m pip install sphinx_rtd_theme

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: doc/_build/html/
        if: success()
