name: "Pull Request Docs Check"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: ammaraskar/sphinx-action@0.4
      with:
        pre-build-command: python -m pip install sphinx_rtd_theme
        build-command: "sphinx-build -b html . _build"
        docs-folder: "doc/"

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: doc/_build/html/
      if: success()
